name: pull builtins.txt from Sei-Lisa's repo

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: fetch builtins.txt
      run: |
        curl -O https://raw.githubusercontent.com/Sei-Lisa/kwdb/master/outputs/builtins.txt
    - name: make builtins_txt.cc
      run: |
        make builtins_txt.cc
    - name: commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add builtins.txt builtins_txt.cc
        git commit -m "update builtins_txt"
        git push
